name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        cd client 
        yarn
    - name: Eslint
      run: |
        cd client 
        yarn check:lint
    - name: TS
      run: |
        cd client 
        yarn check:ts
    - name: Prettier
      run: |
        cd client 
        yarn check:style
    - name: Build
      run: |
        cd client
        yarn build
    - name: Deploy test
      run: |
        cd client
        yarn deploy:test