name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Linter + Prettier
      run: |
        cd client
        yarn
        yarn check:lint
        yarn check:style
