name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2         
    - uses: rlespinasse/github-slug-action@1.1.1
    - name: Install
      run: |
        cd client 
        yarn
    - name: Eslint
      run: |
        cd client 
        yarn check:lint
    - name: TS
      run: |
        cd client 
        yarn check:ts
    - name: Prettier
      run: |
        cd client 
        yarn check:style
    - name: Build
      run: |
        cd client
        yarn build

    - name: Deploy test
      run: |
        cd client
        yarn add surge
        yarn surge --token ${{secrets.SURGE_TOKEN}} --project ./build --domain oren-hakaton-${{ env.GITHUB_HEAD_REF_SLUG }}.surge.sh
